export enum CargoType {
    INDUSTRIAL_EQUIPMENT = 'INDUSTRIAL_EQUIPMENT',
    BIOTECH = 'BIOTECH',
    DROID_PARTS = 'DROID_PARTS'
}

export enum Requirements {
    SHOCK_PROOF = 'SHOCK_PROOF',
    PRESSURE_SEALED = 'PRESSURE_SEALED',
    ANTI_CORROSIVE = 'ANTI_CORROSIVE'
}

export enum Restrictions {
    ACID_RESISTANT = 'ACID_RESISTANT',
    HUMIDITY_SENSITIV = 'HUMIDITY_SENSITIV',
    NO_LIQUIDS = 'NO_LIQUIDS'
}

export enum PlanetType {
    AQUATIC = 'AQUATIC',
    ROCKY = 'ROCKY',
    CORROSIVE = 'CORROSIVE',
}